api_index:
  path: /
  controller: App\Controller\ApiController::index

api_add_trip:
  path: /add-trip
  controller: App\Controller\ApiController::addTrip

api_get_all_trip:
  path: /get-all-trip
  controller: App\Controller\ApiController::getAllTrip

api_get_trip:
  path: /get-trip/{id}
  controller: App\Controller\ApiController::getTrip

api_wish_trip:
  path: /want-trip
  controller: App\Controller\ApiController::wishTrip

api_wish_trip_upd:
  path: /trip/wish
  controller: App\Controller\ApiController::wishTripUpdate

api_conversertions:
  path: /tchat
  controller: App\Controller\ApiController::getAllConversations

api_conversertion_message:
  path: /tchat/messages
  controller: App\Controller\ApiController::getAllMessages
