index:
    path: /
    controller: App\Controller\DefaultController::index

index_cgu:
    path: /cgu
    controller: App\Controller\DefaultController::cgu

index_ml:
    path: /mentions-legales
    controller: App\Controller\DefaultController::ml

index_conf:
    path: /politique-de-confidentialite
    controller: App\Controller\DefaultController::pdc

api_route:
    resource: 'api_routes.yaml'
    prefix: '/api'

security_check_user:
    path: /check-user
    controller: App\Controller\SecurityController::checkUser

security_check_user_admin:
    path: /check-user/admin
    controller: App\Controller\SecurityController::checkUserAdmin

security_login:
    path: /connexion
    controller: App\Controller\SecurityController::login
    methods: ['GET']

security_login_submitted:
    path: /connexion
    controller: App\Controller\SecurityController::loginSubmitted
    methods: ['POST']

security_signup_submitted:
    path: /inscription
    controller: App\Controller\SecurityController::signupSubmitted
    methods: ['POST']

profil_index:
    path: /profil/
    controller: App\Controller\ProfileController::index

user_get:
    path: /utilisateur
    controller: App\Controller\ProfileController::getCurrentUser

security_logout:
    path: /deconnexion

blog_index:
    path: /blog/
    controller: App\Controller\BlogController::index

blog_add:
    path: /blog/add
    controller: App\Controller\BlogController::addArticle

blog_articles:
    path: /blog/articles
    controller: App\Controller\BlogController::getArticles

blog_article:
    path: /blog/article/{slug}
    controller: App\Controller\BlogController::getArticle

blog_article_active:
    path: /blog/article/{slug}/activate
    controller: App\Controller\BlogController::activeArticle

blog_article_refuse:
    path: /blog/article/{slug}/refuse
    controller: App\Controller\BlogController::refuseArticle
