index:
    path: /
    controller: App\Controller\DefaultController::index

api_route:
    resource: 'api_routes.yaml'
    prefix: '/api'

security_login:
    path: /connexion
    controller: App\Controller\SecurityController::login
    methods: ['GET']

security_login_submitted:
    path: /connexion
    controller: App\Controller\SecurityController::loginSubmitted
    methods: ['POST']

security_signup_submitted:
    path: /inscription
    controller: App\Controller\SecurityController::signupSubmitted
    methods: ['POST']

profil_index:
    path: /profil/
    controller: App\Controller\ProfileController::index

user_get:
    path: /utilisateur
    controller: App\Controller\ProfileController::getCurrentUser

security_logout:
    path: /deconnexion
